/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSaljareRouteImport } from './routes/_authenticated/saljare'
import { Route as AuthenticatedRapporterRouteImport } from './routes/_authenticated/rapporter'
import { Route as AuthenticatedProdukterRouteImport } from './routes/_authenticated/produkter'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedOrderRouteImport } from './routes/_authenticated/order'
import { Route as AuthenticatedMaterialRouteImport } from './routes/_authenticated/material'
import { Route as AuthenticatedLonRouteImport } from './routes/_authenticated/lon'
import { Route as AuthenticatedKunderRouteImport } from './routes/_authenticated/kunder'
import { Route as AuthenticatedKampanjerRouteImport } from './routes/_authenticated/kampanjer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAktiviteterRouteImport } from './routes/_authenticated/aktiviteter'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSaljareRoute = AuthenticatedSaljareRouteImport.update({
  id: '/saljare',
  path: '/saljare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapporterRoute = AuthenticatedRapporterRouteImport.update({
  id: '/rapporter',
  path: '/rapporter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdukterRoute = AuthenticatedProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrderRoute = AuthenticatedOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialRoute = AuthenticatedMaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLonRoute = AuthenticatedLonRouteImport.update({
  id: '/lon',
  path: '/lon',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKunderRoute = AuthenticatedKunderRouteImport.update({
  id: '/kunder',
  path: '/kunder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKampanjerRoute = AuthenticatedKampanjerRouteImport.update({
  id: '/kampanjer',
  path: '/kampanjer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAktiviteterRoute =
  AuthenticatedAktiviteterRouteImport.update({
    id: '/aktiviteter',
    path: '/aktiviteter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aktiviteter': typeof AuthenticatedAktiviteterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kampanjer': typeof AuthenticatedKampanjerRoute
  '/kunder': typeof AuthenticatedKunderRoute
  '/lon': typeof AuthenticatedLonRoute
  '/material': typeof AuthenticatedMaterialRoute
  '/order': typeof AuthenticatedOrderRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/produkter': typeof AuthenticatedProdukterRoute
  '/rapporter': typeof AuthenticatedRapporterRoute
  '/saljare': typeof AuthenticatedSaljareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aktiviteter': typeof AuthenticatedAktiviteterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kampanjer': typeof AuthenticatedKampanjerRoute
  '/kunder': typeof AuthenticatedKunderRoute
  '/lon': typeof AuthenticatedLonRoute
  '/material': typeof AuthenticatedMaterialRoute
  '/order': typeof AuthenticatedOrderRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/produkter': typeof AuthenticatedProdukterRoute
  '/rapporter': typeof AuthenticatedRapporterRoute
  '/saljare': typeof AuthenticatedSaljareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aktiviteter': typeof AuthenticatedAktiviteterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kampanjer': typeof AuthenticatedKampanjerRoute
  '/_authenticated/kunder': typeof AuthenticatedKunderRoute
  '/_authenticated/lon': typeof AuthenticatedLonRoute
  '/_authenticated/material': typeof AuthenticatedMaterialRoute
  '/_authenticated/order': typeof AuthenticatedOrderRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/produkter': typeof AuthenticatedProdukterRoute
  '/_authenticated/rapporter': typeof AuthenticatedRapporterRoute
  '/_authenticated/saljare': typeof AuthenticatedSaljareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aktiviteter'
    | '/dashboard'
    | '/kampanjer'
    | '/kunder'
    | '/lon'
    | '/material'
    | '/order'
    | '/pipeline'
    | '/produkter'
    | '/rapporter'
    | '/saljare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aktiviteter'
    | '/dashboard'
    | '/kampanjer'
    | '/kunder'
    | '/lon'
    | '/material'
    | '/order'
    | '/pipeline'
    | '/produkter'
    | '/rapporter'
    | '/saljare'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aktiviteter'
    | '/_authenticated/dashboard'
    | '/_authenticated/kampanjer'
    | '/_authenticated/kunder'
    | '/_authenticated/lon'
    | '/_authenticated/material'
    | '/_authenticated/order'
    | '/_authenticated/pipeline'
    | '/_authenticated/produkter'
    | '/_authenticated/rapporter'
    | '/_authenticated/saljare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saljare': {
      id: '/_authenticated/saljare'
      path: '/saljare'
      fullPath: '/saljare'
      preLoaderRoute: typeof AuthenticatedSaljareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapporter': {
      id: '/_authenticated/rapporter'
      path: '/rapporter'
      fullPath: '/rapporter'
      preLoaderRoute: typeof AuthenticatedRapporterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produkter': {
      id: '/_authenticated/produkter'
      path: '/produkter'
      fullPath: '/produkter'
      preLoaderRoute: typeof AuthenticatedProdukterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order': {
      id: '/_authenticated/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof AuthenticatedOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material': {
      id: '/_authenticated/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof AuthenticatedMaterialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lon': {
      id: '/_authenticated/lon'
      path: '/lon'
      fullPath: '/lon'
      preLoaderRoute: typeof AuthenticatedLonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunder': {
      id: '/_authenticated/kunder'
      path: '/kunder'
      fullPath: '/kunder'
      preLoaderRoute: typeof AuthenticatedKunderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kampanjer': {
      id: '/_authenticated/kampanjer'
      path: '/kampanjer'
      fullPath: '/kampanjer'
      preLoaderRoute: typeof AuthenticatedKampanjerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aktiviteter': {
      id: '/_authenticated/aktiviteter'
      path: '/aktiviteter'
      fullPath: '/aktiviteter'
      preLoaderRoute: typeof AuthenticatedAktiviteterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAktiviteterRoute: typeof AuthenticatedAktiviteterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKampanjerRoute: typeof AuthenticatedKampanjerRoute
  AuthenticatedKunderRoute: typeof AuthenticatedKunderRoute
  AuthenticatedLonRoute: typeof AuthenticatedLonRoute
  AuthenticatedMaterialRoute: typeof AuthenticatedMaterialRoute
  AuthenticatedOrderRoute: typeof AuthenticatedOrderRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProdukterRoute: typeof AuthenticatedProdukterRoute
  AuthenticatedRapporterRoute: typeof AuthenticatedRapporterRoute
  AuthenticatedSaljareRoute: typeof AuthenticatedSaljareRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAktiviteterRoute: AuthenticatedAktiviteterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKampanjerRoute: AuthenticatedKampanjerRoute,
  AuthenticatedKunderRoute: AuthenticatedKunderRoute,
  AuthenticatedLonRoute: AuthenticatedLonRoute,
  AuthenticatedMaterialRoute: AuthenticatedMaterialRoute,
  AuthenticatedOrderRoute: AuthenticatedOrderRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProdukterRoute: AuthenticatedProdukterRoute,
  AuthenticatedRapporterRoute: AuthenticatedRapporterRoute,
  AuthenticatedSaljareRoute: AuthenticatedSaljareRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
