/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlackDebugRouteImport } from './routes/slack-debug'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRapporterRouteImport } from './routes/_authenticated/rapporter'
import { Route as AuthenticatedRapportEkonomiRouteImport } from './routes/_authenticated/rapport-ekonomi'
import { Route as AuthenticatedProduktionRouteImport } from './routes/_authenticated/produktion'
import { Route as AuthenticatedProdukterRouteImport } from './routes/_authenticated/produkter'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedOrderRouteImport } from './routes/_authenticated/order'
import { Route as AuthenticatedMaterialRouteImport } from './routes/_authenticated/material'
import { Route as AuthenticatedLonRouteImport } from './routes/_authenticated/lon'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedKunderRouteImport } from './routes/_authenticated/kunder'
import { Route as AuthenticatedKampanjerRouteImport } from './routes/_authenticated/kampanjer'
import { Route as AuthenticatedFakturaRouteImport } from './routes/_authenticated/faktura'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedAvslutasSnartRouteImport } from './routes/_authenticated/avslutas-snart'
import { Route as AuthenticatedAvslutadRouteImport } from './routes/_authenticated/avslutad'
import { Route as AuthenticatedAnvandareRouteImport } from './routes/_authenticated/anvandare'
import { Route as AuthenticatedAktiviteterRouteImport } from './routes/_authenticated/aktiviteter'

const SlackDebugRoute = SlackDebugRouteImport.update({
  id: '/slack-debug',
  path: '/slack-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRapporterRoute = AuthenticatedRapporterRouteImport.update({
  id: '/rapporter',
  path: '/rapporter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportEkonomiRoute =
  AuthenticatedRapportEkonomiRouteImport.update({
    id: '/rapport-ekonomi',
    path: '/rapport-ekonomi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProduktionRoute = AuthenticatedProduktionRouteImport.update({
  id: '/produktion',
  path: '/produktion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdukterRoute = AuthenticatedProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrderRoute = AuthenticatedOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialRoute = AuthenticatedMaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLonRoute = AuthenticatedLonRouteImport.update({
  id: '/lon',
  path: '/lon',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKunderRoute = AuthenticatedKunderRouteImport.update({
  id: '/kunder',
  path: '/kunder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKampanjerRoute = AuthenticatedKampanjerRouteImport.update({
  id: '/kampanjer',
  path: '/kampanjer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFakturaRoute = AuthenticatedFakturaRouteImport.update({
  id: '/faktura',
  path: '/faktura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvslutasSnartRoute =
  AuthenticatedAvslutasSnartRouteImport.update({
    id: '/avslutas-snart',
    path: '/avslutas-snart',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvslutadRoute = AuthenticatedAvslutadRouteImport.update({
  id: '/avslutad',
  path: '/avslutad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnvandareRoute = AuthenticatedAnvandareRouteImport.update({
  id: '/anvandare',
  path: '/anvandare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAktiviteterRoute =
  AuthenticatedAktiviteterRouteImport.update({
    id: '/aktiviteter',
    path: '/aktiviteter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/slack-debug': typeof SlackDebugRoute
  '/aktiviteter': typeof AuthenticatedAktiviteterRoute
  '/anvandare': typeof AuthenticatedAnvandareRoute
  '/avslutad': typeof AuthenticatedAvslutadRoute
  '/avslutas-snart': typeof AuthenticatedAvslutasSnartRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faktura': typeof AuthenticatedFakturaRoute
  '/kampanjer': typeof AuthenticatedKampanjerRoute
  '/kunder': typeof AuthenticatedKunderRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/lon': typeof AuthenticatedLonRoute
  '/material': typeof AuthenticatedMaterialRoute
  '/order': typeof AuthenticatedOrderRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/produkter': typeof AuthenticatedProdukterRoute
  '/produktion': typeof AuthenticatedProduktionRoute
  '/rapport-ekonomi': typeof AuthenticatedRapportEkonomiRoute
  '/rapporter': typeof AuthenticatedRapporterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/slack-debug': typeof SlackDebugRoute
  '/aktiviteter': typeof AuthenticatedAktiviteterRoute
  '/anvandare': typeof AuthenticatedAnvandareRoute
  '/avslutad': typeof AuthenticatedAvslutadRoute
  '/avslutas-snart': typeof AuthenticatedAvslutasSnartRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faktura': typeof AuthenticatedFakturaRoute
  '/kampanjer': typeof AuthenticatedKampanjerRoute
  '/kunder': typeof AuthenticatedKunderRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/lon': typeof AuthenticatedLonRoute
  '/material': typeof AuthenticatedMaterialRoute
  '/order': typeof AuthenticatedOrderRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/produkter': typeof AuthenticatedProdukterRoute
  '/produktion': typeof AuthenticatedProduktionRoute
  '/rapport-ekonomi': typeof AuthenticatedRapportEkonomiRoute
  '/rapporter': typeof AuthenticatedRapporterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/slack-debug': typeof SlackDebugRoute
  '/_authenticated/aktiviteter': typeof AuthenticatedAktiviteterRoute
  '/_authenticated/anvandare': typeof AuthenticatedAnvandareRoute
  '/_authenticated/avslutad': typeof AuthenticatedAvslutadRoute
  '/_authenticated/avslutas-snart': typeof AuthenticatedAvslutasSnartRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/faktura': typeof AuthenticatedFakturaRoute
  '/_authenticated/kampanjer': typeof AuthenticatedKampanjerRoute
  '/_authenticated/kunder': typeof AuthenticatedKunderRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/lon': typeof AuthenticatedLonRoute
  '/_authenticated/material': typeof AuthenticatedMaterialRoute
  '/_authenticated/order': typeof AuthenticatedOrderRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/produkter': typeof AuthenticatedProdukterRoute
  '/_authenticated/produktion': typeof AuthenticatedProduktionRoute
  '/_authenticated/rapport-ekonomi': typeof AuthenticatedRapportEkonomiRoute
  '/_authenticated/rapporter': typeof AuthenticatedRapporterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/slack-debug'
    | '/aktiviteter'
    | '/anvandare'
    | '/avslutad'
    | '/avslutas-snart'
    | '/budget'
    | '/dashboard'
    | '/faktura'
    | '/kampanjer'
    | '/kunder'
    | '/leads'
    | '/lon'
    | '/material'
    | '/order'
    | '/pipeline'
    | '/produkter'
    | '/produktion'
    | '/rapport-ekonomi'
    | '/rapporter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/slack-debug'
    | '/aktiviteter'
    | '/anvandare'
    | '/avslutad'
    | '/avslutas-snart'
    | '/budget'
    | '/dashboard'
    | '/faktura'
    | '/kampanjer'
    | '/kunder'
    | '/leads'
    | '/lon'
    | '/material'
    | '/order'
    | '/pipeline'
    | '/produkter'
    | '/produktion'
    | '/rapport-ekonomi'
    | '/rapporter'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/slack-debug'
    | '/_authenticated/aktiviteter'
    | '/_authenticated/anvandare'
    | '/_authenticated/avslutad'
    | '/_authenticated/avslutas-snart'
    | '/_authenticated/budget'
    | '/_authenticated/dashboard'
    | '/_authenticated/faktura'
    | '/_authenticated/kampanjer'
    | '/_authenticated/kunder'
    | '/_authenticated/leads'
    | '/_authenticated/lon'
    | '/_authenticated/material'
    | '/_authenticated/order'
    | '/_authenticated/pipeline'
    | '/_authenticated/produkter'
    | '/_authenticated/produktion'
    | '/_authenticated/rapport-ekonomi'
    | '/_authenticated/rapporter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SlackDebugRoute: typeof SlackDebugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slack-debug': {
      id: '/slack-debug'
      path: '/slack-debug'
      fullPath: '/slack-debug'
      preLoaderRoute: typeof SlackDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rapporter': {
      id: '/_authenticated/rapporter'
      path: '/rapporter'
      fullPath: '/rapporter'
      preLoaderRoute: typeof AuthenticatedRapporterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapport-ekonomi': {
      id: '/_authenticated/rapport-ekonomi'
      path: '/rapport-ekonomi'
      fullPath: '/rapport-ekonomi'
      preLoaderRoute: typeof AuthenticatedRapportEkonomiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produktion': {
      id: '/_authenticated/produktion'
      path: '/produktion'
      fullPath: '/produktion'
      preLoaderRoute: typeof AuthenticatedProduktionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produkter': {
      id: '/_authenticated/produkter'
      path: '/produkter'
      fullPath: '/produkter'
      preLoaderRoute: typeof AuthenticatedProdukterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order': {
      id: '/_authenticated/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof AuthenticatedOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material': {
      id: '/_authenticated/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof AuthenticatedMaterialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lon': {
      id: '/_authenticated/lon'
      path: '/lon'
      fullPath: '/lon'
      preLoaderRoute: typeof AuthenticatedLonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunder': {
      id: '/_authenticated/kunder'
      path: '/kunder'
      fullPath: '/kunder'
      preLoaderRoute: typeof AuthenticatedKunderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kampanjer': {
      id: '/_authenticated/kampanjer'
      path: '/kampanjer'
      fullPath: '/kampanjer'
      preLoaderRoute: typeof AuthenticatedKampanjerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faktura': {
      id: '/_authenticated/faktura'
      path: '/faktura'
      fullPath: '/faktura'
      preLoaderRoute: typeof AuthenticatedFakturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avslutas-snart': {
      id: '/_authenticated/avslutas-snart'
      path: '/avslutas-snart'
      fullPath: '/avslutas-snart'
      preLoaderRoute: typeof AuthenticatedAvslutasSnartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avslutad': {
      id: '/_authenticated/avslutad'
      path: '/avslutad'
      fullPath: '/avslutad'
      preLoaderRoute: typeof AuthenticatedAvslutadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anvandare': {
      id: '/_authenticated/anvandare'
      path: '/anvandare'
      fullPath: '/anvandare'
      preLoaderRoute: typeof AuthenticatedAnvandareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aktiviteter': {
      id: '/_authenticated/aktiviteter'
      path: '/aktiviteter'
      fullPath: '/aktiviteter'
      preLoaderRoute: typeof AuthenticatedAktiviteterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAktiviteterRoute: typeof AuthenticatedAktiviteterRoute
  AuthenticatedAnvandareRoute: typeof AuthenticatedAnvandareRoute
  AuthenticatedAvslutadRoute: typeof AuthenticatedAvslutadRoute
  AuthenticatedAvslutasSnartRoute: typeof AuthenticatedAvslutasSnartRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFakturaRoute: typeof AuthenticatedFakturaRoute
  AuthenticatedKampanjerRoute: typeof AuthenticatedKampanjerRoute
  AuthenticatedKunderRoute: typeof AuthenticatedKunderRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLonRoute: typeof AuthenticatedLonRoute
  AuthenticatedMaterialRoute: typeof AuthenticatedMaterialRoute
  AuthenticatedOrderRoute: typeof AuthenticatedOrderRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProdukterRoute: typeof AuthenticatedProdukterRoute
  AuthenticatedProduktionRoute: typeof AuthenticatedProduktionRoute
  AuthenticatedRapportEkonomiRoute: typeof AuthenticatedRapportEkonomiRoute
  AuthenticatedRapporterRoute: typeof AuthenticatedRapporterRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAktiviteterRoute: AuthenticatedAktiviteterRoute,
  AuthenticatedAnvandareRoute: AuthenticatedAnvandareRoute,
  AuthenticatedAvslutadRoute: AuthenticatedAvslutadRoute,
  AuthenticatedAvslutasSnartRoute: AuthenticatedAvslutasSnartRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFakturaRoute: AuthenticatedFakturaRoute,
  AuthenticatedKampanjerRoute: AuthenticatedKampanjerRoute,
  AuthenticatedKunderRoute: AuthenticatedKunderRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLonRoute: AuthenticatedLonRoute,
  AuthenticatedMaterialRoute: AuthenticatedMaterialRoute,
  AuthenticatedOrderRoute: AuthenticatedOrderRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProdukterRoute: AuthenticatedProdukterRoute,
  AuthenticatedProduktionRoute: AuthenticatedProduktionRoute,
  AuthenticatedRapportEkonomiRoute: AuthenticatedRapportEkonomiRoute,
  AuthenticatedRapporterRoute: AuthenticatedRapporterRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SlackDebugRoute: SlackDebugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
